### ISSUE TITLE
problem in prediction :value error-valueerror: shape mismatch: objects cannot be broadcast to a single shape

### ISSUE THREAD

**Issue by Radhika-Gupta5** [deep-diver/CIFAR10-img-classification#3] opened 2018-10-30 07:23 UTC
In CIFAR10_image_classification.ipynb notebook in the last cell I am facing an issue with the display_image_predictions function . I have used your code as it is. It is showing only the testing accuracy. Pl help .

**Comment by deep-diver** [comment] 2018-10-30 07:27
Do you see any error message or something? please make sure that

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

is included in the code cell where test_model() is defined.

**Comment by Radhika-Gupta5** [comment] 2018-10-30 07:41
Yes, I have added both of these lines in the code. 

The error is:
valueerror: shape mismatch: objects cannot be broadcast to a single shape
Screenshots:
![screenshot 23](https://user-images.githubusercontent.com/37223166/47703139-4a2b3580-dc45-11e8-9845-066e6665f92f.png)
![screenshot 24](https://user-images.githubusercontent.com/37223166/47703149-52837080-dc45-11e8-81ea-70a67279d9ed.png)

**Comment by deep-diver** [comment] 2018-10-30 07:45
I am curiouse on which lines of code the error pops up.

**Comment by Radhika-Gupta5** [comment] 2018-10-30 07:47
When we call the display_image_predictions function.

**Comment by deep-diver** [comment] 2018-10-30 07:48
I meant which line in the display_image_predictions function.

**Comment by Radhika-Gupta5** [comment] 2018-10-30 07:52
Screenshots of the errors in the display_image_predictions function:
![screenshot 25](https://user-images.githubusercontent.com/37223166/47703615-d9851880-dc46-11e8-9557-308d18e0933d.png)
![screenshot 26](https://user-images.githubusercontent.com/37223166/47703627-e30e8080-dc46-11e8-97be-b6b2ef22f0d0.png)

**Comment by deep-diver** [comment] 2018-10-30 08:45
I have made an updated commit. Please check it out.
sorry for the inconvenience, and thank you for reporting this issue.

if you think the problem is fixed, please close this issue.

**Comment by smartrads5** [comment] 2018-10-30 08:58
Thanks! The error has been resolved . We want to store the first predicted label in a variable for further use. How to do that ?

**Comment by deep-diver** [comment] 2018-10-30 09:07
Since that is not an issue about this project, i will close this issue. 
You could ask me via email. Thanks.

**Closed as completed** 2018-10-30 09:07 UTC

**Comment by Radhika-Gupta5** [comment] 2018-10-30 09:08
Yes I closed the issue. Thankyou so much . It was a great help.

Regards
Radhika

**Comment by Radhika-Gupta5** [comment] 2018-12-15 07:51
Hello

In your code for CIFAR -CNN Classification it is showing top 3 predictions
I want to get to only the 1st one and want to store it in a variable for
further use. Please help as I am new to deep learning in python .


Regards

Radhika
